### PR TITLE
add ability to filter meal plans based on type

### PR DESCRIPTION
**Pull request by smilerz**
I thought there was a feature request for this but I can't find it.

### CODE REVIEW

**Comment by vabene1111** [comment]
i kinda wanted to do that when i changed the frontend but I lacked UI skills to make it look nice so I never did the endpoint for it 😂 

do you think we should make this a list parameter to allow filtering for multiple types?

**Comment by smilerz** [comment]
Yes. Probably.  I'll take a look at it this weekend.

**Comment by vabene1111** [comment]
i think there are other endpoints that take lists with get parameters, feel free to copy logic from there

**Comment by smilerz** [comment]
lol you think I can do anything other than copy code :-)

**Comment by smilerz** [comment]
This adds multiple meal_types as part of the API filter.  Should be good to merge now.

**Pull request merged**
