### PR TITLE
docs: :memo: Add Hebrew readme

### PR DESCRIPTION
**Pull request by YonLiud**
## docs: :memo: Add Hebrew readme

I added the Hebrew translation as part of my journey to translate all projects and applications I use on a daily basis to invite more Hebrew Speakers and Israelis into using those apps.

In case this PR gets accepted I will attempt to translate all of the rest of the markdown files requiring translation!

### CODE REVIEW

**Comment by vabene1111** [comment]
hi, thank you very much for your contribution. I must think of what i want to do with translations of the main readme as it leads to a few questions if we start to translate it into multiple languages

- what happens if the main readme is update, i wont be able to update other langugages and people who have made the translation are unavailable
- how does this look on github/generally if the main directory becomes full of translated readme/doc files

what you can definitely do is translate the application itself using translate.tandoor.dev, i think most people who are able to install a docker container can read the few words of english required to understand what needs to be done but the application users might not be. 

When it comes to the docs i think i would prefer having the real docs (docs.tandoor.dev) translated instead of the readme, i will look into the library we use for the docs to see if multi language switching is something that can easily be done and also supports incomplete translations (e.g. show English if no local version is available)

**Comment by YonLiud** [comment]
> what happens if the main readme is update, i wont be able to update other langugages and people who have made the translation are unavailable

I honestly believe that the people are into translating this project will do exactly the same

> how does this look on github/generally if the main directory becomes full of translated readme/doc files

It will appear as a normal Markdown file and will not change the structure very much, and once more translations become available others will understand how to open these files depending on their most comfortable language

**Comment by vabene1111** [comment]
ok so i tought a bit longer about this and decided that everything can be translated except for the projects readme file. So feel free to take a look at the application on translate.tandoor.dev or take a crack at the docs. 

I dont have the time to try it out but the docs will probably best use this plugin for mkdocs https://pypi.org/project/mkdocs-static-i18n/ 

Also all translations should include a small info box on the top to show that they are community translations and not offically maintained, feel free to try out a PR, if not I will take a look at some point as I wanted to add some german translation anyway.

**Comment by vabene1111** [comment]
ok so i wanted to add the plugin to the docs but for some reason its giving me an error, I have asked the plugin author for help, maybe he can point out what i am missing

https://github.com/ultrabug/mkdocs-static-i18n/issues/145

**Comment by YonLiud** [comment]
> ok so i wanted to add the plugin to the docs but for some reason its giving me an error, I have asked the plugin author for help, maybe he can point out what i am missing
> 
> [ultrabug/mkdocs-static-i18n#145](https://github.com/ultrabug/mkdocs-static-i18n/issues/145)

Well, I ain't no professional at mkdocs but I will sure look into ``translate.tandoor.dev`` for sure to contribute!

**Comment by vabene1111** [comment]
Awesome thanks, I will try to get mkdocs working

**Comment by vabene1111** [comment]
ok so i got mkdocs fixed with the maintiner, props to him for the fast and very helpful reaction but i have decided that for now i want to hold off on transaltions in the docs. 

its just extra work for me and I can barely handle the amount currently so i simply cannot sustain that.

**Comment by YonLiud** [comment]
understandable, relatable, and unquestionable

**Pull request closed without merging**
