### PR TITLE
improve developer instructions

### PR DESCRIPTION
**Pull request by MarcusWolschon**
Improve instructions on how to start the development environment.

### CODE REVIEW

**Comment by vabene1111** [comment]
awesome, thanks, that makes sense. Ldap is stupid to install on windows.

**Comment by MarcusWolschon** [comment]
A few additional words about translations could be useful.
Not how to translate existing strings but how to add and test new strings.

**Comment by vabene1111** [comment]
closed for compliance reasons

**Comment by MarcusWolschon** [comment]
Added more text about compiling translations and running unit tests.

**Pull request closed without merging**
