### PR TITLE
lock down yarn dependencies

### LINKED ISSUE #1091: Add `yarn.lock` for front-end dependencies
**Is your feature request related to a problem? Please describe.**

I want to be able to reproducibly build Tandoor Recipes. However there is no `yarn.lock` file to pin node dependencies to specific versions.

**Describe the solution you'd like**

Instead of ignoring `vue/yarn.lock`, it should be committed and updated, similarly to how the `requirements.txt` is handled for python modules.

**Describe alternatives you've considered**

Using a `yarn.lock` file exterior to the project, however this requires manual intervention to check that the lock file is still up to date when trying to bump the version of Tandoor Recipes.

**Additional context**

My personal context is being in the process of packaging this project for NixOS.

### PR DESCRIPTION
**Pull request by ambroisie**
Reasoning explained in the corresponding issue.

Closes #1091.

### CODE REVIEW

**Comment by vabene1111** [comment]
thanks, i will look at merging this or maybe, because i cant review the file, regenerate the lock file on my client just for security reasons (not that i mistrust you but its safer this way). Thanks for pointing out the issue and showing the solution.

**Comment by ambroisie** [comment]
@vabene1111 no problem, I just wanted to make an MR rather than just open an issue and make demands, given that I was able to easily solve it.

Feel free to close this MR and do it yourself if you'd rather.

**Comment by vabene1111** [comment]
thanks, that is very welcome 👍

**Comment by vabene1111** [comment]
added with next release, thanks for helping :)

**Pull request closed without merging**
