### PR TITLE
Added existence check for Nginx config file and mandatory parameters

### PR DESCRIPTION
**Pull request by MaxJa4**
Checks on Web-Container startup, whether the Nginx configuration file (Recipes.conf) is present.
If it's not present - which would prohibit Nginx from working properly (see #1531) - a warning is shown.

If GUNICORN_MEDIA is not 0 (0 is default) and therefore Nginx is not used, no warning will be shown.

Path to config file is hardcoded, but there is no point in changing the mounting point in the docker-compose file anyway and the warning doesn't prohibit the startup - it's just to make issue analysis for the users and developers easier.

### CODE REVIEW

**Comment by MaxJa4** [comment]
I would also add a check for the existence of the security key and postgres-pw since the are required...
Since we recently had a discussion about that in Discord, I'm waiting for your OK on that.
Would be a temporary solution ofc, until these checks are done in the UI or the .env is restructured :)

**Comment by vabene1111** [comment]
i think a warning on startup, no matter on what solution we choose to implement for variables/config, is always good if a required setting is not there and helps debugging, so go ahead and thank you very much for all these little but very impactful tweaks and changes you are making 👍

**Comment by vabene1111** [comment]
i will leave this open until you have the variables done so you dont need two PRs

**Comment by MaxJa4** [comment]
Done.

Worst case (no nginx config found + both variables not set) looks like this:
```
Checking configuration...
[WARNING]
Nginx configuration file could not be found at the default location!
Path: /opt/recipes/nginx/conf.d/Recipes.conf
[WARNING]
The environment variable 'SECRET_KEY' is not set but REQUIRED for running Tandoor!
[WARNING]
The environment variable 'POSTGRES_PASSWORD' is not set but REQUIRED for running Tandoor!
Waiting for database to be ready...
Database is ready
Migrating database
[...]
```

**Comment by vabene1111** [comment]
awesome, thank you 👍

**Pull request merged**
