### PR TITLE
fixes recipe export

### LINKED ISSUE #2698: Recipe export error "There was an error loading a resource!" in develop
### Tandoor Version

vabene1111/recipes:develop

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Other

_No response_

### Bug description

Lost recipe export functionality in "develop" branch.
Message "There was an error loading a resource!"

Full functional in "latest"

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by smilerz**
fixes #2698

### CODE REVIEW

**Comment by BstAA** [comment]
Sorry, but still not fully fixed. Seams no download link ist generated.

- no automatic download
- no link AND
- message "Expired"

see screen shot

Screenshot 2023-10-28 125835

Tested with MS-Edge and Firefox.

**Exception**:
1. One recipe
> - restart browser / new login
> - select only _one_ recipe for export
> - Link is generated and automated download started
> - back to "export" 
> - select another single recipe --> Error see above

2. All 
> - restart browser / new login
> - select _all_ recipes for export
> - --> Error see above

**Comment by smilerz** [comment]
That's a different known problem.  Hit refresh and the download should start.

**Comment by BstAA** [comment]
THX! Didn't find this problem in the issues list. Have you got a # for me?

**Comment by stleusc** [comment]
> That's a different known problem. Hit refresh and the download should start.

Depending on the size of the download you have to wait a few extra seconds. And it does NOT always work either...

**Pull request merged**
