### PR TITLE
show ingredients in edit view

### PR DESCRIPTION
**Pull request by stleusc**
show ingredients in edit view regardless if they are hidden in read view

This will fix issue #2704

### CODE REVIEW

**Comment by vabene1111** [comment]
thanks for the PR, I need to look more closely into this as from my memory these two functions should not have anything to do with each other, but I will verify that

**Comment by stleusc** [comment]
Well that's the point ...
And the original author confirmed that the functionality was changed.
Surprised a one line PR takes months....
________________________________

**Comment by vabene1111** [comment]
surprised people still think open source software maintainers are people they can expect to work around the clocks on things offered for free to everyone ...

**Comment by stleusc** [comment]
Best part about open source is, one can just clone the project and be done.
Sad to see that some let their ego get in the way of improvements.
________________________________

**Comment by vabene1111** [comment]
I really dont understand your attitude, I was on vacation for some weeks and had to catch up with work after that but you feel like insulting me for properly verifying the functionality of a PR. I dont wan't to count someone like that to my contributers so when I have time I will look at the issue and fix it myself, until then it just has to wait.

**Pull request closed without merging**
