### PR TITLE
#1552 import recipes from cookidoo

### PR DESCRIPTION
**Pull request by MarcusWolschon**
Implement feature request #1552 by adding a custom importer for cookidoo

### CODE REVIEW

**Comment by vabene1111** [comment]
Could you contribute this directly to the recipe scrapers library? This way it would be centrally maintained and tested and everyone would benefit from it, also non tandoor users

**Comment by MarcusWolschon** [comment]
No, the actual scraping is already completely in the Recipe Scrapers Library and gets inherited.
This just overrides 2 behaviors that the library deliberately does in a different way to the stregth and weaknesses of TandoorRecipes

1)
They explicitely converts the recursive list of steps into a string.
I overrides that function to get the flat list Tandoor can handle but other clients using the library can't.
That's the contract of that method in all parsers and I can't adjust all other parsers to add a second method in the interface.
https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/_schemaorg.py#L225

2)
Also the conversion of custom Unicode characters Cookiedoo uses is an adjustment to the limitations of TandoorRecipes because we can't add the custom font Cookiedoo uses in it's CSS to display the symbols matching the . (At the very least for interlectual property reasons.)
I can't possibly make that choice for apps using the library 

I am contemplating donating other improvements directly to the Scraper library.
Such as code to handle ingredient units that contain a space "geh. Löffel"/"heaped spoon".
They would benefit everyone and are not specific to the abilities and limitations of TandoorRecipes.

**Comment by MarcusWolschon** [comment]
@vabene1111 I found that the Recipe Scrapers Library already offers a method instructions_list() instead of the flat instructions() we used, so I could get rid of a specialized cookiedoo scraper.
I moved the handling of the Thermomix-speific instructions into an existing cleanup method.

**Comment by vabene1111** [comment]
hi, thanks. While (as stated in the other PR) i dislike hardcoded lists I guess thermomix is large enough so that it makes sense in this case. 

I haven't looked at the differentce between instructions and flat_instructions, is there anything that could break in other parser due to this change? Have you tested the change with different sites/the test suite ?

**Comment by MarcusWolschon** [comment]
I tested a number of randomly chosen recipe-sites and they where all imported correctly with steps.
Section headers become their own step, wich is the best we can do without a concept of sections.

**Comment by vabene1111** [comment]
ok thanks. Reviewing this now I still dont understand why the cleanup methods should reside in Tandoor? Everyone using recipe scrapers to parse cookidoo recipes would benefit from the replacement so it would be better there. 
One thing that recipe scrapers currently cant do is localize so maybe the text would need to be handled by emoji's or something similar. 

I also dont know the difference between the two instruction functions yet but could't the old function be fixed in recipe-scrapers directly so that it follows the same structure as all other parsers?

**Comment by MarcusWolschon** [comment]
I did look at custom python markdown extensions to handle this on the display-side but could not find where the instance of "markdown" is created in Tandoor to add a 4th extension to it.
https://python-markdown.github.io/extensions/api/

**Comment by MarcusWolschon** [comment]
I tried to use the existing "automation" function "keyword replace" to do replace the custom UTF-8 characters,
but it doesn't seem to work.
I guess "keyword" here means tags.

I guess I could give the existing automation a string-replacements for steps in addition to the existing tags, ingredients and foods.
Then this part could be moved to a user configuration instead of being hardcoded.
This PR could be reduced to just instructions() -> instructions_list() and there would be no hardcoded replacements in the codebase anymore.
@vabene1111  What do you think? Should I implement that?

**Comment by vabene1111** [comment]
dont have time to write much but

- replacing the charcters the way you do it is fine with me, with emojis i meant actual emojis (standard ones) but not sure if there are proper fitting ones, probably not
- i see that the localization in recipe scrapers is difficult, i dont really like it but its probably best to leave it in tandoor
- i do not want to change instructions() to instructions list as that would change the behavior of all importers. instructions list only splits instructions on linebreaks which the frontend of tandoor is already able to do.


so i guess only two changes necessary
- remove instructions list as the frontend can handle this
- change the default locale to English as this is the default locale everywhere (even tough I understand why you did it since thermomix is primarily german)

**Comment by MarcusWolschon** [comment]
done

**Comment by MarcusWolschon** [comment]
@vabene1111 Just pinging, take your time. Just making sure it's not forgotten.
The changes you wanted have been done 3 weeks ago.

**Comment by vabene1111** [comment]
thanks, i know. Will get this merged when I find It appropriate for the release cycle.

**Comment by jmvargas** [comment]
Hello @vabene1111 , is this going to me accepted soon? it would be a nice feature

**Comment by vabene1111** [comment]
This will be accepted when I accept it. Nobody pays and only few people thank me for working on this project so I do what I can but my time is limited.

**Pull request merged**
