### PR TITLE
Display options upon importing duplicate recipe URL

### PR DESCRIPTION
**Pull request by lavanyamehn**
The user can either continue to import a duplicate recipe or edit the existing recipe. This addresses issue #2857.

### CODE REVIEW

**Comment by lavanyamehn** [comment]
I have already signed the CLA. Also, with respect to the "not to be a GitHub user" issue, is it because my email on my account is private?

**Comment by vabene1111** [comment]
Hi, thanks for your PR.

Since I am currently working on #2976 I am not entirely sure if I want to merge this into the existing branch.

Also I think I would prefer if the API endpoint returned a list of existing recipes with the same URL and the client just showed an warning (found existing recipes with the same URL). This would reduce complexity and solve the issue just as well. What do you think.

**Comment by vabene1111** [comment]
> I have already signed the CLA. Also, with respect to the "not to be a GitHub user" issue, is it because my email on my account is private?

Honestly I am not sure, so far it has worked for everyone, if you did it its fine for me.

**Comment by lavanyamehn** [comment]
> Hi, thanks for your PR.
> 
> Since I am currently working on #2976 I am not entirely sure if I want to merge this into the existing branch.
> 
> Also I think I would prefer if the API endpoint returned a list of existing recipes with the same URL and the client just showed an warning (found existing recipes with the same URL). This would reduce complexity and solve the issue just as well. What do you think.

Sure, I can remove the options I added (edit existing recipe and continue to import) and only display a warning message so the user can continue to import like normal.

Regarding the status of this PR, if you don't think it will get merged in the near future I am wondering if there is any other good first issue I can work on to support #2976. Contributing to open-source projects and getting a PR merged in is part of one of my courses so it would be great if you could guide me on how best to approach this, thanks!

**Comment by lavanyamehn** [comment]
> > I have already signed the CLA. Also, with respect to the "not to be a GitHub user" issue, is it because my email on my account is private?
> 
> Honestly I am not sure, so far it has worked for everyone, if you did it its fine for me.

Screenshot 2024-11-23 at 9 31 23 AM
This is what I see when I open the link, so not sure about it.

**Comment by vabene1111** [comment]
thank you very much. Yes please make it so that the only change for now is just a "warning" message in the importer when it detects a duplicate (maybe by annotating a field to the response).

Regarding your other question: Sadly its currently pretty hard to contribute as some technical fundamentals need to be implemented first. What are the parts you would like to work on most, frontend or backend ?

**Comment by lavanyamehn** [comment]
Updated this PR to only display a warning message.

If there is a small beginner friendly task on the backend, I could try to help.

**Pull request closed without merging**
