### PR TITLE
add admin command to delete unattached ingredients and steps

### PR DESCRIPTION
**Pull request by smilerz**
creates two admin actions:
- delete all Ingredients not part of a recipe
- delete all Steps not part of a recipe

### CODE REVIEW

**Comment by tomtjes** [comment]
@smilerz Could the same be done for foods?

**Comment by smilerz** [comment]
> @smilerz Could the same be done for foods, units and keywords?

theoretically - but I wouldn't implement it.  There are valid scenarios where food and keywords especially, are intentionally unused (root of hierarchy in my personal use case) - allowing mass deletion in those cases would likely lead to unintended outcomes.

**Comment by tomtjes** [comment]
That makes sense. I have a hacky script that deletes unused keywords and foods (and checks that they don't have children in the hierarchy) via the API, and had hoped for a simpler solution to get rid of clutter that inevitably comes with importing web recipes.

**Comment by smilerz** [comment]
Eventually we’ll add filters and multi-edit capabilities to the management page.

**Pull request merged**
