### PR TITLE
Refactor Docker CI: Consolidate, add cache, GHCR Repository, major/minor tags

### LINKED ISSUE #2375: Support a container registry other than Docker Hub
### Is your feature request related to a problem? Please describe.

Hello!

Yesterday, Docker sent an email stating they will be removing open source organizations within the next month, described by [this unofficial blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/).

Since then, Docker has apologized for the miscommunication in [this official blog post](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), but I still feel that Docker Hub may not be a safe provider of open source container images anymore.

### Describe the solution you'd like

Push your images to an additional registry like [GHCR](https://ghcr.io) or [Quay](https://quay.io).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gabe565**
This PR consolidates the various Docker build scripts, along with adding some new features.

## Changes

- Consolidate various Docker build workflows
  - I did this by using a matrix for the Standard and Raspi builds. The Raspi builds are allowed to fail so that they don't affect the standard builds or the release notifications.
- Replace [`ilteoood/docker_buildx`](https://github.com/ilteoood/docker_buildx) with [`docker/build-push-action`](https://github.com/docker/build-push-action)
  - I also added the [`docker/metadata-action`](https://github.com/docker/metadata-action) to handle most of the tag logic
- Add major and minor Docker tags (e.g `vabene1111/recipes:1` and `vabene1111/recipes:1.4`
- Enable yarn cache and Docker build cache to improve CI speed
- Add a GHCR repository at `ghcr.io/TandoorRecipes/recipes` to fix #2375. This should be created by the CI when this PR is merged and a build is triggered. The new GHCR package will also be listed below the "Releases" section in the homepage of this repository.
- Remove the "release published" trigger. The `latest` tag is now included in the "tag pushed" trigger.
- Bump [actions/setup-node](https://github.com/actions/setup-node) from v2 to v3
- Bump [DamianReeves/write-file-action](https://github.com/DamianReeves/write-file-action) from v1.0 to v1.2
- Replace [deprecated `::set-output` command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) with `$GITHUB_OUTPUT`

## Testing Criteria

To test this PR, I created a temporary GHCR repository in my fork, tested various different edge-cases, and checked the resulting Docker tags:

- Pushed to a feature branch at `feature/consolidate-ci-scripts`:
  - Standard tags: `feature-consolidate-ci-scripts`
  - Raspi tags: `feature-consolidate-ci-scripts-raspi` (this is new, but it doesn't hurt to have a Raspi tag for feature branches)
- Pushed to `develop` branch:
  - Standard tags: `develop`
  - Raspi tags: `develop-raspi`
- Pushed to `beta` branch:
  - Standard tags: `beta`
  - Raspi tags: `beta-raspi`
  - Beta notification was triggered
- Created a new tag/release:
  - Standard tags: `latest`, `1.4.9`, `1.4`, `1`
  - Raspi tags: `latest-raspi`, `1.4.9-raspi`, `1.4-raspi`, `1-raspi`
  - Stable notification was triggered
- Caused Raspi build to fail:
  - Standard build passed
  - Raspi build failed
  - Notification was still triggered

Please verify that I didn't miss any edge-cases. I ran diffs over all of the separate CI workflows to verify, but it's possible that I missed something.

Let me know if you have any questions or suggestions!

### CODE REVIEW

**Comment by vabene1111** [comment]
Very very awesome, thank you so much not only for the code but also well documented and written PR

Will look trough it and get it merged together with your other contribution.

One thing we need to make sure is that the image size does not increase, I don't think so but sometimes docker behaves strangely here

**Comment by gabe565** [comment]
Thank you! I'm glad to contribute.

That will be easy to verify since I have the images pushed to my fork's ghcr repo! Give me a moment and I'll post a comparison

**Comment by gabe565** [comment]
They look similar to me. My fork's `beta` images are smaller, but I suspect that's because I built against a more recent commit and is unrelated to this change. The `develop` image is much closer in size.

| Tag          | Old Build | New Build |
|--------------|-----------|-----------|
| `beta`       | 445MB     | 396MB     |
| `beta-raspi` | 405MB     | 355MB     |
| `develop`    | 392MB     | 396MB     |

**Comment by vabene1111** [comment]
ok perfect, thank you very much for improving this.

**Comment by gabe565** [comment]
@vabene1111 I noticed Dependabot builds are failing after merging this. I was nervous this would happen, but was hopeful that setting `permissions` on the job would fix it. This is happening because Dependabot PRs use a separate secrets source than regular commits.

There are two ways that I can think of to fix this:
1. Go to Settings > Secrets and variables > Dependabot and set your DockerHub credentials there. Then rerun one of the Dependabot builds and we'll see if they pass.
2. I could completely disable pushing of Docker images from Dependabot PRs. It would still perform a build to ensure the dependency update doesn't break anything, but it would not push to either repository.

Let me know if you have a preference either way!

**Comment by gabe565** [comment]
@vabene1111 Oh and one more thing. I believe the GHCR package defaulted to being private. When you get a chance, could you go to https://ghcr.io/TandoorRecipes/recipes > Package Settings > Change package visibility > Public

**Comment by vabene1111** [comment]
thanks for verifying everything is working. 

1. i set the package to public, please confirm you can see it now
2. i do not think that i will ever need to pull the image for a deperndabot PR. I think I prefer it not being published, checking if it builds obviously makes sense but after that I will probably just fix it an push a fix to dev once updated so if you could disable that easily that would be awesome.

**Comment by gabe565** [comment]
Awesome, I can see the image! 🎉 One more thing you could do if you want to show this image on the repo's homepage is go to the homepage, click the settings cog in the about section on the right, and turn on "Packages" in the home page.

Also, sounds great. I'll create a quick PR to skip pushes for Dependabot PRs

**Comment by vabene1111** [comment]
awesome, thank you very much, saved me a lot of working getting this stuff all setup and working

**Pull request merged**
