### PR TITLE
Added Back To Top Button

### LINKED ISSUE #2135: Adding a Bottom to Top button so that user go on top by clicking on that.
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the solution you'd like

Adding a button at bottom for going top i.e.,

image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by n8thanwai**
Added a "Back To Top" Button on every page to resolve #2135

Commented code in the base.html file that was added to add the new feature. 

No Hover....
back2top

Hover...
back2top-hover

### CODE REVIEW

**Comment by rmartini24** [comment]
@vabene1111 would you mind reviewing?

**Comment by vabene1111** [comment]
Please fix the inclusion of an external bootstrap version, one is already included.

**Comment by n8thanwai** [comment]
I have removed the external bootstrap version. Please let me know if there is anything else that I can change.

**Comment by vabene1111** [comment]
hi, the code appears to be copied from somewhere else, is the license of the external source permissive enough so that using the code without proper source attribution is ok 

https://github.com/search?q=%3Cbutton+onclick%3D%22topFunction%28%29%22+id%3D%22back-to-top%22&type=code

**Comment by n8thanwai** [comment]
Hi, after digging deeper into the issue, we have reviewed the licensing for w3schools that we mirrored the JS code from. Although after consulting with the terms we are unsure whether a citation is necessary, however, we have committed a new citation comment to the pull request.

**Comment by vabene1111** [comment]
ok thanks, need to test how this looks on mobile on all the different pages since you embedded the button in the base not only in the list view

**Pull request closed without merging**
