### PR TITLE
Test execution performance improvements

### PR DESCRIPTION
**Pull request by smilerz**
created TEST_DATABASE settings in env - define database for testing purposes
added test_settings.py to apply settings only required for testing
added pytest param to run tests in parrallel
removed middleware and installed apps not required during testing
removed coverage reports from repo

local testing improved from 5531 seconds to 112 seconds

### CODE REVIEW

**Comment by vabene1111** [comment]
wow the tests took very long for you but the improvement is great.

Do I see it correctly that your remove deprecated settings PR is kinda already included in this one now?
Why did you decide to remove coverage stuff now, didn't we add that just a few weeks ago?

**Comment by smilerz** [comment]
I don't know how the deprecated settings got included?  I must have rebased off the wrong branch.  I'll fix that.  

The coverage change is a mistake - I was trying to isolate the source of the delays, I'll fix that too.

**Comment by vabene1111** [comment]
ok thanks, i thought that was intentional.

**Comment by smilerz** [comment]
Cancelled and replaced with PR #3052

**Pull request closed without merging**
