### PR TITLE
Update connectors.md

### PR DESCRIPTION
**Pull request by supaeasy**
Fixed errors in description:
- add / after api
- omit 'todo.' when adding HA-Entity

### CODE REVIEW

**Comment by vabene1111** [comment]
thank you for the update!

**Comment by vabene1111** [comment]
@mikhail5555 can you look into if this should be reverted ?

**Comment by supaeasy** [comment]
Sorry for the hassle!

**Comment by vabene1111** [comment]
thank you for the feedback, going to revert this.

**Comment by supaeasy** [comment]
Thank you for your offer @mikhail5555 I will contact you once I am back from vacation, some 10ish days or so. Maybe you could look into my question [here ](https://github.com/TandoorRecipes/recipes/issues/911#issuecomment-2387229381) about deleting or checking items in the API in the meantime. I am still getting all of my imported recipes into structure but would like to go "productive" with one solution or the other - though I think my way would fit my needs better since it includes all the details I want for bring list.

**Pull request merged**
