### PR TITLE
Api enhancements

### PR DESCRIPTION
**Pull request by smilerz**

### CODE REVIEW

**Comment by vabene1111** [comment]
what was changed here so I have something to write in the changelog ?

**Comment by smilerz** [comment]
Sorry, I forgot to copy the changes from the commits to the PR.
Paginated steps and updated the List view to use pages.
Paginated automations.
Added a filter on the automations API for automation type.

**Comment by vabene1111** [comment]
perfect, this makes more sense now. Can you rebase or should I merge?

**Comment by smilerz** [comment]
> perfect, this makes more sense now. Can you rebase or should I merge?

You can merge - I think the only conflict is on imports.  I tried to rebase, but am having IDE struggles

**Pull request merged**
