### PR TITLE
#1093 Recipe link in plan

### PR DESCRIPTION
**Pull request by MarcusWolschon**
#1093 add a recipe link into meal plan

I'm not experiences with Vue or Javascript development in general.
So please feel free to do any cleanup you see fit.

I coult not find a way to hide the context menu item if no receipt was linked to the meal plan entry.

### CODE REVIEW

**Comment by smilerz** [comment]
> I coult not find a way to hide the context menu item if no receipt was linked to the meal plan entry.

Does this mean that `v-if` did not work?  or you didn't know the syntax?

**Comment by MarcusWolschon** [comment]
> > I coult not find a way to hide the context menu item if no receipt was linked to the meal plan entry.
> 
> Does this mean that `v-if` did not work? or you didn't know the syntax?

I don't know the syntax and if it works within a context menu element.
This is the first time I've even seen Vue.

**Comment by smilerz** [comment]
> I don't know the syntax and if it works within a context menu element. This is the first time I've even seen Vue.

Understood - I don't know if it will work there or not.  None of the contributors have worked with Vue before, so we are all learning as we go.  The [Vue documentation](https://vuejs.org/v2/api/) is pretty good, StackOverflow has lots of examples as does this project.
In general, you can add `v-if="object.attribute"` to any class and it will check for truthiness.

**Comment by MarcusWolschon** [comment]
@smilerz done and tested

**Comment by vabene1111** [comment]
i would say this does not fix the related issue as the basic issue is that for some reason the dynamically loaded component does not render for some users (while working for others). 
This is of cours a good workaround and generally good feature until @Kaibu gets around to investigate why the recipe card is not rendered.

**Comment by vabene1111** [comment]
the code looks fine but why did you put most of the code into the html tag directly and made a function for the navigate to url ?

I think i would prefer if the code was in a function as well, something like open recipe. This is only a minor thing but i am traveling and cant quickly change this so it would be great if you could do that. Also please use `==!` for the comparison to avoid possible JS bullshit.

**Comment by MarcusWolschon** [comment]
Because in the function it could not resolve the resolveDjangoUrl() function.

**Comment by MarcusWolschon** [comment]
Noted.
Can't promise I'll have time to learn how to do this tomorrow.
The nutritional values import is more important for me.

**Comment by vabene1111** [comment]
i am on vacation for the next few days anyway so no hurry.

**Comment by MarcusWolschon** [comment]
Couldn't find out how to import that function.
Needs a JavaScript developer to clean that up.

**Comment by vabene1111** [comment]
sorry for being so picky in this and some other PRs but if it works like this reviewing, merging and updating a PR like this is simply more work than doing the feature myself. 

you can simply use `this.resolveDjangoUrl("view_recipe", recipe.id)` when the function is imported as a mixin as seen in recipe switche line 96

**Comment by MarcusWolschon** [comment]
Done

**Comment by vabene1111** [comment]
this does not really do what i wanted (move most of the code from the JS @click inline code to the function but i will just implement this myself now to get this unblocked.

**Pull request merged**
