### PR TITLE
add rating to recipe card

### PR DESCRIPTION
**Pull request by smilerz**

### CODE REVIEW

**Comment by vabene1111** [comment]
is there a reason the meal plan edito modal is included in this PR? It seems you ran one of the formatters over it and I cannot really find any actual changes?

**Comment by smilerz** [comment]
> is there a reason the meal plan edito modal is included in this PR? It seems you ran one of the formatters over it and I cannot really find any actual changes?

Sorry, VSCode formats on save and I don't always remember to disable it.   

This prop was added - but is never referenced.  I think you can safely discard changes to that file.
`entryEditing_inital_servings: Number,`

**Comment by vabene1111** [comment]
ok i just screwed this up completely by trying to delete MealPlanEditModal from the PR but it deleted the file as a commit ... since i cannot push on your repo from a git client could you revert that and also revert the previous changes you have done to the file so that I can merge it?

**Comment by vabene1111** [comment]
perfect, thank you very much

**Pull request merged**
