### PR TITLE
prefetch food relations #1965

### PR DESCRIPTION
**Pull request by 8633brown**
This solves two n+1 problems for the FoodViewSet

### CODE REVIEW

**Comment by vabene1111** [comment]
awesome, thank you for the fix. I really need to get around to reviewing the complete search system

**Comment by 8633brown** [comment]
No worries. I could be wrong but I think there's some extra API calls on some of the pages from what I can see but I've not looked at any of the js side of it. 

I was going to have a look at the FoodSerializer.get_substitute_onhand method next. I think this has a similar issue. I think it's requesting the on hand alternatives for every Food item it iterates over.

**Comment by vabene1111** [comment]
yes, there are quite a few api requests that could be consolidated. 

generally speaking i am torn between completely rewriting the entire search/food/unit system or trying to dig into all the tiny things that cause performance issues (multiple calls, subsitutes, the tree system, usage count informations, ...)

**Comment by 8633brown** [comment]
Yeah that's fair. I was going primarily for the quick wins with what my situation is. 
Which at the moment is running on a pi which is pretty slow so I figured I could muddle my way through try to help out on improving some queries (expecting it to be easier than a refactor). At least that benefits everyone quicker than I rewrite.

**Comment by vabene1111** [comment]
thats awesome, there are likely many low hanging fruits that could be implemented first before attemting a rewrite, feel free to fix everything you want.

**Pull request merged**
