### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by hyperbit00**
typo in ressource

### CODE REVIEW

**Review by turnbeutelvergesser — COMMENTED** [review]
The original text was correct, I think.  Zu "dem" Rezept umwandeln, hence "Zu interne_m_ Rezept".

**Comment by hyperbit00** [comment]
> The original text was correct, I think. Zu "dem" Rezept umwandeln, hence "Zu interne_m_ Rezept".

Mhh, If I look at
Https://de.m.wiktionary.org/wiki/Flexion:intern
I See the Second table Dativ: "dem internen"

**Comment by turnbeutelvergesser** [comment]
Yes, but then you'd need to use "Zu_m_ interne_n_ Rezept umwandeln" which does not sound natural, because you don't use the Dativ in that case.

**Comment by vabene1111** [comment]
after accidentally merging please do not make PRs to master! 
also i agree that `m` is correct in this context.

i fixed Ressource manually

**Pull request merged**
