### PR TITLE
Added sub-recipe ingredients below the main recipe ingredients. 

### LINKED ISSUE #1993: Add subrecipe ingredients to main list
### Is your feature request related to a problem? Please describe.

When adding a (sub)recipe to a recipe the ingredients of that subrecipe aren't added tot ingredients list at the top of the main recipe. 

### Describe the solution you'd like

When adding a subrecipe add the ingredients to the top of the mainrecipe ingredients list with a header naming the subrecipe.

_pepper symbol_ Ingredients
ingredient 1 
ingredient 2 
ingredient 3 
etc..

_Name subrecipe_
Subrecipe ingredient 1
subrecipe ingredient 2 
etc...

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by czsanborn**
Resolves #1993. 
Before: 
original ingredient organization
After:
added sub-recipe ingredients

### CODE REVIEW

**Comment by vabene1111** [comment]
Thank you very much for that PR and sorry for the late response. 

This will significantly increase the size of the ingredient list but thats already a design issue of the recipe view so nothing for you to worry about. 

What do you think about putting the sub list into a expandable box that only opens when clicked or do you think thats confusing for the user?

**Comment by czsanborn** [comment]
I like that idea. I can implement it and see how it looks.

**Comment by czsanborn** [comment]
I made the sub-ingredients list collapsible. 
Here is what it looks like closed and open:
sub-ingredient list closed
sub-ingredient list opened
Let me know if you have any other suggestions or feedback!

**Comment by vabene1111** [comment]
Very nice, thanks for the quick implementation. I will get it merged and maybe add a small plus/minus or caret button to indicate the behavior while doing so.

Thank you for the pr

**Comment by czsanborn** [comment]
I had some free time, so I went ahead and added the caret, but feel free to make any changes. Thank you!
Closed:
sub-ingredient button closed
Open:
sub-ingredient button open

**Comment by vabene1111** [comment]
awesome, thanks, i really like that. Will get it merged for the next release

**Review by vabene1111 — APPROVED** [review]

**Comment by MattSidney** [comment]
@vabene1111 did this get merged in? on a separate PR?

**Comment by vabene1111** [comment]
I don't think this ever got merged, not sure exactly why, will look at it at some point

**Comment by vabene1111** [comment]
no longer makes sense as new frontend will need to re do this anyway

**Pull request closed without merging**
