### PR TITLE
moved validation from part of step to part of recipe

### PR DESCRIPTION
**Pull request by smilerz**
prior attempt checked if food is part of ingredient__step but some foods that are not part of a recipe are still part of an orphaned step.  Moved validation to checking if part of recipe.  Also added check to prevent deleting food that has children that are part of recipes.  Modified Unit to allow deletion of orphaned units that are part of Ingredient and/or Step but are not linked to a Recipe.

### CODE REVIEW

**Comment by vabene1111** [comment]
Thanks for this fix, just to make sure

- orphaned steps are something that i want to allow in the long term (as i want to allow using steps in multiple recipes independently) so this change should not remove ingredients/foods/units that are part of a step that currently has no recipe ?

**Comment by smilerz** [comment]
> Thanks for this fix, just to make sure
> 
> * orphaned steps are something that i want to allow in the long term (as i want to allow using steps in multiple recipes independently) so this change should not remove ingredients/foods/units that are part of a step that currently has no recipe ?

oh - yes, it does do that.  I had a bunch of food/units that were attached to orphaned steps with no way to manage that - which is what prompted the change.

**Comment by vabene1111** [comment]
hmm what do you think about a management page to clear unused foods/units/keywords and also steps ? 

Could be integrated on the space page next to the statistics or something like that ?

**Comment by vabene1111** [comment]
or we implement one of the standard split list views for steps with the future perspecive of adding a filter that allows to filter for "unused" items 🤔 could be something to be included in the StandardFilterMixin and a model function to find unused entries depending on the model

**Comment by smilerz** [comment]
> hmm what do you think about a management page to clear unused foods/units/keywords and also steps ?
> 
> Could be integrated on the space page next to the statistics or something like that ?

IDK - mass deleting things makes me nervous.  But some way to manage steps/ingredients is necessary if enforcing ref-integrity on food/units

> or we implement one of the standard split list views for steps with the future perspecive of adding a filter that allows to filter for "unused" items 🤔 could be something to be included in the StandardFilterMixin and a model function to find unused entries depending on the model

There are definitely some 'standard' filters I've been thinking about for awhile. So this idea appeals.

> that would go hand in hand with the multi select option we talked about a while ago (i think, maybe i just thought about that feature ..)

I have a bulk edit feature for the model page mostly designed in my head.

**Comment by vabene1111** [comment]
ok so bulk edit and some standardized way of filtering for the model list views it is! Does that make this PR irrelevant or shoudl i still merge it ?

**Comment by smilerz** [comment]
Yes and no - if you don't want to delete food/units from orphaned steps it definitely needs changed.

**Comment by vabene1111** [comment]
we could delete them for now but i fear that we might forget about this once we implement "step independence" and then delete stuf that should not be deleted. 

This also comes down to the question of when we are going to make steps independent, are we going to delete previously orphaned steps or keep them around ...

**Comment by smilerz** [comment]
it would only matter if that step that should be 'saved' isn't part of any recipe.  But putting it on hold until further progress has been made makes sense.

RE: step independence - I can see some instructions being really useful.  I'd like to see embedding multiple pictures as very useful in that scenario (e.g. here are pictures how to butterfly a whole chicken)

**Comment by vabene1111** [comment]
yes, some better way to integrate images both to steps and recipes is definitely needed. I added the "files" system as a quick workaround but it does not actually resovle the fundamental issues. 

I will take a look at this at some point hopefully soon.

**Pull request closed without merging**
