### PR TITLE
Docs: Inline docker-compose.yaml files in the documentation

### PR DESCRIPTION
**Pull request by tuxuser**
This change includes docker-compose.yml files inline in the documentation built by `mkdocs`.
It ensures the documentation is always on-par with the files commited.

### CODE REVIEW

**Comment by vabene1111** [comment]
Very cool thank you, I like that. Can you fix that it says exposes port 8 instead of 80 or is this just displayed wrong on the GitHub app?

**Comment by tuxuser** [comment]
It's just displayed wrong

**Comment by vabene1111** [comment]
ok awesome, i see it now on my laptop. Thanks for the PR

**Comment by vabene1111** [comment]
ok i just merged this and the CI run deployed the docs but its not working. Sadly running out of time right now so will revert this for now, probably just a little path issue or something

**Pull request merged**
