### PR TITLE
Keep screen awake when viewing recipe

### LINKED ISSUE #1434: Prevent switching display off after OS timeout
### Is your feature request related to a problem? Please describe.

If you are cooking a recipe from your Tandoor recipe instance on a mobile device the display switches off after the timeout declared in the setting of your OS. Some apps, e.g. [Chefkoch](https://play.google.com/store/apps/details?id=de.pixelhouse&referrer=utm_source%3Dchefkoch.de%26utm_medium%3Dbanner%26utm_content%3Dmagazin_top%26utm_campaign%3Dchefkoch.generalcamp) keeps the display on.

### Describe the solution you'd like

Keep the display on

### Describe alternatives you've considered

_No response_

### Additional context

Maybe i can implement this on my own. I am able to contribute python code, but never worked with django

### Contribute

- [X] Yes
- [X] Partly
- [ ] No

### PR DESCRIPTION
**Pull request by benscobie**
To resolve #1434

This is rather basic, at some point you could add a switch to toggle this functionality on & off.

### CODE REVIEW

**Comment by vabene1111** [comment]
awesome, thanks for implementing this. I need to review this since i dont know much about this function but i am pretty sure it should work. Since i have my phone never turn off i never even noticed that this is a problem 😂

**Comment by vabene1111** [comment]
ok just checked the vue lifecylcle docs, beforeUnmount seems to be a vue 3 lifecycle hook so i changed that to beforeDEstory, otherwise this seems correct, thanks for the contribution!

**Comment by vabene1111** [comment]
ok it appears that this is indeed available in v2 as well but not in the docs .. ok staying with unmount then ..

**Comment by ccoenen** [comment]
it should be noted that there is limited browser support for `navigator.wakeLock` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/wakeLock), [caniuse](https://caniuse.com/mdn-api_wakelock)). Neither mobile firefox nor iOS Safari support this. So the only benefit is to Chrome users on android.

**Pull request merged**
