### PR TITLE
Added some translations in meal plan, recipe search and recipe switcher.

### PR DESCRIPTION
**Pull request by MaxJa4**
Added some new translations to vue's and translated some to DE while I was at it.
The rest is probably easier via Weblate.

### CODE REVIEW

**Comment by vabene1111** [comment]
very interesting, i just merged the other PR which included only one file change yet it merged this one as well 🤔 whatever, thank you for this commit as well :)

**Comment by MaxJa4** [comment]
Seems like the revert, that cleaned up the other PR, messed up this PR (however that's possible). These changes here are not applied now :(

**Comment by vabene1111** [comment]
thats not good. can you just PR again from your branch, should detect those changes

**Comment by MaxJa4** [comment]
Created a new PR with just the translation changes from this PR.

**Pull request merged**
