### PR TITLE
Update the baseimage of dockerfile as alpine 3.12 has some security v…

### PR DESCRIPTION
**Pull request by xMAC94x**
…unerabilities.

According to:
https://artifacthub.io/packages/helm/truecharts/recipes?modal=security-report&image=tccr.io%2Ftruecharts%2Frecipes%3Av1.0.5%40sha256%3Ac74923879e7d2bf5bff4d1e953a100307462ad191a79908165f3364b97446833
There are at least 4 Chritical ones with a total of 47.
So updating the base should prob be a good thing and help here.

### CODE REVIEW

**Comment by xMAC94x** [comment]
While Alpine 3.12 still is actilvy supported, that python build was last updated 7 month ago:
https://hub.docker.com/layers/python/library/python/3.9-alpine3.12/images/sha256-25f3cfeaceca14921366af4d1240b56457ef46273bdb508c7b0e8f469f6fd228?context=explore

**Comment by MaxJa4** [comment]
Just saw that the CI pipeline runs on Python 3.10 but the Dockerfile has 3.9... so maybe that can be changed as well, since testing will be required anyway after bumping up Alpine to 3.15.

**Comment by xMAC94x** [comment]
> Just saw that the CI pipeline runs on Python 3.10 but the Dockerfile has 3.9... so maybe that can be changed as well, since testing will be required anyway after bumping up Alpine to 3.15.

updated Dockerfile to python 3.10, done :)

**Comment by vabene1111** [comment]
aweseome, thanks for paying attention! Did you already test if that image works ?

**Comment by MaxJa4** [comment]
Not yet, but I'll test it today (again on RPI4 and VPS probably) :)

**Comment by MaxJa4** [comment]
Building issues on ARM based systems (RPI)... investigating later.

**Comment by vabene1111** [comment]
awesome, thanks for all the work here 👍 i will try to get this merged soon

**Comment by xMAC94x** [comment]
> ```
> echo -n "INPUT ( libldap.so )" > /usr/lib/libldap_r.so
> ```

Thank you, also added that finding here :)

**Pull request merged**
